# Generated by Django 4.2.7 on 2023-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_car_student_delete_reciepe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rciepe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reciepe_name", models.CharField(max_length=100)),
                ("reciepe_descriptin", models.TextField()),
                ("reciepe_image", models.ImageField(upload_to="reciepe")),
            ],
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
