# Generated by Django 4.2.7 on 2023-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="recipe_photos"),
        ),
    ]
