# Generated by Django 4.2.7 on 2023-12-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipe", "0002_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_photos"),
        ),
    ]
