# Generated by Django 4.2.7 on 2023-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_reciepe_delete_car_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="Reciepe",
        ),
    ]
